[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; FatFS als Dateisystem verwenden
board_build.filesystem = fatfs
board_build.partitions = partitions.csv

; Upload-Einstellungen
monitor_speed = 115200
upload_speed = 921600
