name: Examples

on:
  workflow_dispatch:      # Manually start a workflow
  push:
    paths-ignore:
    - '.github/**'        # Ignore changes towards the .github directory
    - '**.md'             # Do no build if *.md files changes

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        example:
          - "examples/tasmota"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -U https://github.com/Jason2866/platformio-core/archive/refs/tags/v6.1.16.tar.gz
          pio pkg install --global --platform symlink://.
      - name: git clone Tasmota and add to examples
        if: "matrix.example == 'examples/tasmota' && matrix.os != 'windows-2022'"
        run: |
          git clone -b development --recursive --depth 1 --shallow-submodule https://github.com/arendst/Tasmota.git examples/tasmota
          cp examples/tasmota_platformio_override.ini examples/tasmota/platformio_override.ini
      - name: Build examples
        if: "matrix.example != 'examples/tasmota' || matrix.os != 'windows-2022'"
        run: |
          pio run -d ${{ matrix.example }}
